// <auto-generated />
using System;
using DoAn_QLSV.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAn_QLSV.Migrations
{
    [DbContext(typeof(QLSVDbContext))]
    [Migration("20250526091409_KhoiTaoCSDL_Lan1")]
    partial class KhoiTaoCSDL_Lan1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAn_QLSV.Data.DiemHocTap", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("diemHe4")
                        .HasColumnType("real");

                    b.Property<float>("diemHocTap")
                        .HasColumnType("real");

                    b.Property<string>("maHocKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maMonHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("xepLoaiHocTap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("MSSV");

                    b.HasIndex("maHocKy");

                    b.HasIndex("maMonHoc");

                    b.ToTable("DiemHocTap");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.DiemRenLuyen", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("diemRenLuyen")
                        .HasColumnType("real");

                    b.Property<string>("maHocKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("xepLoaiRenLuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("MSSV");

                    b.HasIndex("maHocKy");

                    b.ToTable("DiemRenLuyen");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.HocKy", b =>
                {
                    b.Property<string>("maHocKy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("namHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenHocKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maHocKy");

                    b.ToTable("HocKy");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.Khoa", b =>
                {
                    b.Property<string>("maKhoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.Lop", b =>
                {
                    b.Property<string>("maLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("maKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maLop");

                    b.HasIndex("maKhoa");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.MonHoc", b =>
                {
                    b.Property<string>("maMonHoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("soTinChi")
                        .HasColumnType("int");

                    b.Property<string>("tenMonHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maMonHoc");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.TaiKhoan", b =>
                {
                    b.Property<string>("tenDangNhap")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phanQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tenDangNhap");

                    b.HasIndex("MSSV");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.ThongTinSinhVien", b =>
                {
                    b.Property<string>("MSSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhoamaKhoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lopID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ngaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("soDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MSSV");

                    b.HasIndex("KhoamaKhoa");

                    b.HasIndex("lopID");

                    b.ToTable("ThongTinSinhVien");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.DiemHocTap", b =>
                {
                    b.HasOne("DoAn_QLSV.Data.ThongTinSinhVien", "SinhVien")
                        .WithMany("DiemHocTap")
                        .HasForeignKey("MSSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_QLSV.Data.HocKy", "HocKy")
                        .WithMany("DiemHocTap")
                        .HasForeignKey("maHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_QLSV.Data.MonHoc", "MonHoc")
                        .WithMany("DiemHocTap")
                        .HasForeignKey("maMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.DiemRenLuyen", b =>
                {
                    b.HasOne("DoAn_QLSV.Data.ThongTinSinhVien", "SinhVien")
                        .WithMany("DiemRenLuyen")
                        .HasForeignKey("MSSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_QLSV.Data.HocKy", "HocKy")
                        .WithMany("DiemRenLuyen")
                        .HasForeignKey("maHocKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.Lop", b =>
                {
                    b.HasOne("DoAn_QLSV.Data.Khoa", "Khoa")
                        .WithMany("Lop")
                        .HasForeignKey("maKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.TaiKhoan", b =>
                {
                    b.HasOne("DoAn_QLSV.Data.ThongTinSinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MSSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.ThongTinSinhVien", b =>
                {
                    b.HasOne("DoAn_QLSV.Data.Khoa", null)
                        .WithMany("SinhVien")
                        .HasForeignKey("KhoamaKhoa");

                    b.HasOne("DoAn_QLSV.Data.Lop", "Lop")
                        .WithMany("SinhVien")
                        .HasForeignKey("lopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.HocKy", b =>
                {
                    b.Navigation("DiemHocTap");

                    b.Navigation("DiemRenLuyen");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.Khoa", b =>
                {
                    b.Navigation("Lop");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.Lop", b =>
                {
                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.MonHoc", b =>
                {
                    b.Navigation("DiemHocTap");
                });

            modelBuilder.Entity("DoAn_QLSV.Data.ThongTinSinhVien", b =>
                {
                    b.Navigation("DiemHocTap");

                    b.Navigation("DiemRenLuyen");
                });
#pragma warning restore 612, 618
        }
    }
}
